shallow_clone: true
version: '{branch}-{build}'
cache:
  - C:\projects\qutebrowser\.cache
build: off

image:
  - Visual Studio 2015  # Windows Server 2012 R2 / Windows 8
  - Visual Studio 2019  # Windows Server 2019 / Windows 10

environment:
    PYTHONUNBUFFERED: 1
    PYTHON: C:\Python38-x64\python.exe
    TESTENV: py38-pyqt514

install:
  - '%PYTHON% --version'
  - '%PYTHON% -m pip install -U pip'
  - '%PYTHON% -m pip install -r misc\requirements\requirements-tox.txt'
  - 'set PATH=C:\Python37-x64;%PATH'

test_script:
  - '%PYTHON% -m tox -e %TESTENV%'
