shallow_clone: true
version: '{branch}-{build}'
cache:
  - C:\projects\qutebrowser\.cache
build: off
environment:
    PYTHONUNBUFFERED: 1
    matrix:
    - TESTENV: py34
    - TESTENV: unittests-frozen
    - TESTENV: pylint

install:
  - C:\Python27\python -u scripts\dev\ci\appveyor_install.py

test_script:
  - C:\Python34\Scripts\tox -e %TESTENV%
