name: Rebuild Docker CI images

on:
  workflow_dispatch:
  schedule:
    - cron: "23 5 * * *"  # daily at 5:23

jobs:
  docker:
    if: "github.repository == 'qutebrowser/qutebrowser'"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - archlinux-webkit
          - archlinux-webengine
          - archlinux-webengine-unstable
          - archlinux-webengine-unstable-qt6
          - archlinux-webengine-qt6
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install jinja2
      - name: Generate Dockerfile
        run: python3 generate.py ${{ matrix.image }}
        working-directory: scripts/dev/ci/docker/
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: qutebrowser
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          file: scripts/dev/ci/docker/Dockerfile
          context: .
          tags: "qutebrowser/ci:${{ matrix.image }}"
          push: ${{ github.ref == 'refs/heads/main' }}

  irc:
    timeout-minutes: 2
    continue-on-error: true
    runs-on: ubuntu-20.04
    needs: [docker]
    if: "always() && github.repository == 'qutebrowser/qutebrowser'"
    steps:
      - name: Send success IRC notification
        uses: Gottox/irc-message-action@v2
        if: "needs.docker.result == 'success'"
        with:
          server: irc.libera.chat
          channel: '#qutebrowser-bots'
          nickname: qutebrowser-bot
          message: "[${{ github.workflow }}] \u00033Success:\u0003 ${{ github.ref }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} (@${{ github.actor }})"
      - name: Send non-success IRC notification
        uses: Gottox/irc-message-action@v2
        if: "needs.docker.result != 'success'"
        with:
          server: irc.libera.chat
          channel: '#qutebrowser-bots'
          nickname: qutebrowser-bot
          message: "[${{ github.workflow }}] \u00034FAIL:\u0003 ${{ github.ref }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} (@${{ github.actor }})"
